### ISSUE TITLE
question about  CUTSITE

### ISSUE THREAD

**Issue by DaiyuanLiu** [suda-huanglab/circlehunter#11]
Dear Dr.Yang,
    Thanks for your useful tool. I have a question about the cutsites.py script that why the value of flag 83 is reference_start rather than reference_end? It seems that the "163: 'reference_start'" and "83: 'reference_start'" point to the same chromosome coordinate.
   Looking forward to your reply.
<img width="160" alt="Snipaste_2024-03-07_15-53-22" src="https://github.com/suda-huanglab/circlehunter/assets/113338915/d1ff8bbc-7917-485e-9067-4e12880b36e8">

**Comment by yangmqglobe** [comment]
I remember that cutsites.py is not used in the main pipeline, so it is not tested.

**Comment by DaiyuanLiu** [comment]
> I remember that cutsites.py is not used in the main pipeline, so it is not tested.

But I found cutsites.py in accessible.smk, and found accessible.smk in "Snakefile". Can I take the "Snakefile" file as the main pipeline?

**Comment by yangmqglobe** [comment]
No, the main pipeline only include rules that generate result of rule `all` in Snakefile, please check out [snakemake document](https://snakemake.readthedocs.io/en/stable/tutorial/basics.html#step-7-adding-a-target-rule)

**Comment by DaiyuanLiu** [comment]
> No, the main pipeline only include rules that generate result of rule `all` in Snakefile, please check out [snakemake document](https://snakemake.readthedocs.io/en/stable/tutorial/basics.html#step-7-adding-a-target-rule)

So the accessible.smk won't be run if I run Snakefile? The cutsites.py is invoked in the accessible.smk.
![image](https://github.com/suda-huanglab/circlehunter/assets/113338915/152ac5ba-4ffc-46d4-b037-de4f059adf8c)

**Comment by yangmqglobe** [comment]
Yes，the main pipeline use bam2bed.py to generete accessible tag.

**Comment by DaiyuanLiu** [comment]
> Yes，the main pipeline use bam2bed.py to generete accessible tag.

The bam2bed.py is the first step of accessible.smk. What about the cutsites section? Is it useless?
![image](https://github.com/suda-huanglab/circlehunter/assets/113338915/0e6beb7d-5f59-4130-a1d0-1bc38b94b325)

**Comment by yangmqglobe** [comment]
That may be a test steps, but I found that adjust Tn5 cutsize is not proper for ecDNA breakpoint calling, so that is not used.

**Comment by DaiyuanLiu** [comment]
> That may be a test steps, but I found that adjust Tn5 cutsize is not proper for ecDNA breakpoint calling, so that is not used.

I got it. Thank you.
