### ISSUE TITLE
请问一下Circle-seq测序数据能使用这款软件吗？

### ISSUE THREAD

**Issue by liyugo** [suda-huanglab/circlehunter#9]
我想使用您的软件研究复杂结构的ecDNA，但是只有Circle-seq测序数据，所以想请教一下，Circle-seq这种测序是否可以使用这款软件呢？

**Comment by yangmqglobe** [comment]
理论上可以，因为circle-seq对ecDNA的富集程度更高，但可能某些参数需要调整。

**Comment by liyugo** [comment]
感谢您的快速答复，我会尝试一下，看能否得到结果。

**Comment by liyugo** [comment]
我使用软件的原始参数测试了Circle-seq，是可以得出ecDNA的，感谢非常不错的软件~

**Comment by liyugo** [comment]
您好，再次叨扰。
再次检查结果的时候，我发现我的结果比较难理解，下面展示GSM3832731_ecDNA.bed的前6行。我猜测第7列到第10列为同一个ecDNA的多个片段，但是每一个ecDNA都有4个片段比较异常，所以我想向您问一下，从第7列开始是什么含义。如果我得到的结果有误，我想向您请教一下解决的方法，附上两个样本得到的ecDNA bed文件和使用的yaml文件。

1. `chr2    128829234       128831688       ecDNA_1_1_1     .       +       128829233-128829235     128831687-128831689     128827838-128830279     128830712-128833030     796.6303        10`
2. `chr2    97858331        97868509        ecDNA_2_1_1     .       +       97858331-97858336       97868504-97868509       97856862-97861680       97864342-97871900       649.1955        98`
3. `chr2    64347133        64351239        ecDNA_3_1_1     .       +       64347133-64347138       64351234-64351239       64345680-64349306       64349821-64352699       195.3733        23`
4. `chr4    183145220       183151096       ecDNA_4_1_1     .       +       183145220-183145227     183151089-183151096     183143759-183147173     183147576-183152565     188.593 50`
5. `chr4    6029249 6032495 ecDNA_5_1_1     .       +       6029249-6029252 6032492-6032495 6027786-6030749 6030995-6033964 134.98  52`
6. `chr6    112008480       112013077       ecDNA_6_1_1     .       +       112008480-112008488     112013069-112013077     112007048-112010269     112011468-112015364     111.64200000000001      10`

[GSM383_ecDNA.zip](https://github.com/suda-huanglab/circlehunter/files/13225534/GSM383_ecDNA.zip)

**Comment by yangmqglobe** [comment]
输出文件各个列的意义如下：
1. chrom，染色体
2. start，片段起点
3. end，片段终点
4. ecDNA_{n}\_{t}\_{p}，片段名字，其中 `{n}` 为ecDNA编号，`{t}` 为该ecDNA的片段总数，`{p}` 为当前片段编号
5. .，无意义
6. strand，片段接入 ecDNA 的方向
7. start_ci，片段起点的置信区间
8. end_ci，片段终点的置信区间
9. pr1，片段起点的富集区
10. pr2，片段终点的富集区
11. fold_enrich，片段的富集倍数
12. link_reads，与下一片段链接的 reads 计数

单个 ecDNA 可能由多个片段组成，具体要看第4列，`{n}`  一样的片段就是一个 ecDNA，这些片段按照 `{p}` 的顺序以第6列的方向首尾相接连接成 ecDNA。

**Comment by liyugo** [comment]
原来如此，非常感谢您细致且耐心的回答，再次感谢！！
